# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='parking', max_length=255),
            preserve_default=False,
        ),
    ]
