# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
