# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total',
        ),
    ]
